name: Spakuj i wrzuć na CurseForge

on:
  push:
    tags: 
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{secrets.API_KEY}}
      
    steps:
      - name: Klonowanie repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # gets entire git history, needed for automatic changelogs

      - name: Pakowanie i upload
        uses: BigWigsMods/packager@v2
        with:
            args: -g cata -p 1028809 -l -o -n "{package-name}_{project-version}_{project-timestamp}:{package-name}_{project-version}"
            
