name: "Build Release"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Upload to CurseForge
          uses: itsmeow/curseforge-upload@v3.1.2
          with:
                file_path: "/archive/refs/heads/main.zip"
                game_endpoint: "wow"
                game_versions: "4.4.0"
                project_id: "1028809"
                token: "de2bf86b-5b30-4664-81aa-810f7ff5a5f5"
                display_name: "TEST"
                release_type: "alpha"
